name: Build Kernel
on: 
  workflow_dispatch:
    inputs:
      LineageOS_Version:
        description: LineageOS Version
        required: true
        type: string
jobs:
  build: 
    runs-on: ubuntu-22.04
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "JackyLu0520"
          git config --global user.name "JackyLu0520"
      
      - name: Install dependencies
        run: |
          sudo apt remove firefox google-chrome-stable
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y git ccache make flex bison bc cpio \
          python3 python3-dev python-is-python3 \
          build-essential curl libssl-dev libelf-dev libdw-dev \
          zip unzip device-tree-compiler libncurses5 unifdef
      
      - name: Setup clang
        uses: actions/checkout@v7
        with:
          repository: LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b
          path: clang
          fetch-depth: 0
          ref: lineage-20.0

      - name: Setup gcc
        uses: actions/checkout@v7
        with:
          repository: LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9
          path: gcc
          fetch-depth: 0
          ref: lineage-19.1
      
      - name: Setup gcc32
        uses: actions/checkout@v7
        with:
          repository: LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9
          path: gcc32
          fetch-depth: 0
          ref: lineage-19.1
      
      - name: Checkout defconfig
        uses: actions/checkout@v7
        with:
          path: defconfig
          fetch-depth: 0

      - name: Checkout kernel source
        uses: actions/checkout@v7
        with:
          repository: LineageOS/android_kernel_oneplus_sm8750
          path: kernel
          fetch-depth: 0
          ref: lineage-${{github.event.inputs.LineageOS_Version}}
      
      - name: Checkout sm8750-modules
        uses: actions/checkout@v7
        with:
          repository: LineageOS/android_kernel_oneplus_sm8750-modules
          path: sm8750-modules
          fetch-depth: 0
          ref: lineage-${{github.event.inputs.LineageOS_Version}}
      
      - name: Checkout sm8750-devicetrees
        uses: actions/checkout@v7
        with:
          repository: LineageOS/android_kernel_oneplus_sm8750-devicetrees
          path: sm8750-devicetrees
          fetch-depth: 0
          ref: lineage-${{github.event.inputs.LineageOS_Version}}

      - name: Fix kernel/sched/walt/walt_halt.c(Temporarily?)
        run: |
          sed -i 's/#include <walt.h>/#include "walt.h"/' kernel/kernel/sched/walt/walt_halt.c

      - name: Fix certs/extract-cert.c(Temporarily?)
        run: |
          ls -la kernel/certs/
          unifdef -DUSE_PKCS11_ENGINE kernel/certs/extract-cert.c -o kernel/certs/extract-cert.c
      
      - name: Build Kernel
        run: |
          export USE_CCACHE=1
          export CCACHE_EXEC=/usr/bin/ccache
          ccache -M 4G

          CLANGDIR=$PWD/clang
          GCCDIR=$PWD/gcc
          GCCDIR32=$PWD/gcc32

          cd kernel
          make mrproper
          cp ../defconfig/erhai_defconfig arch/arm64/configs

          args="ARCH=arm64 \
            PATH=$CLANGDIR/bin:$GCCDIR/bin:$PATH \
            LD_LIBRARY_PATH=$CLANGDIR/lib \
            LLVM=1 \
            CROSS_COMPILE=$GCCDIR/bin/aarch64-linux-android- \
            CROSS_COMPILE_ARM32=$GCCDIR32/bin/arm-linux-androideabi- \
            CLANG_TRIPLE=aarch64-linux-gnu-"

          make ${args} erhai_defconfig

          make ${args} -j4
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Image
          path: arch/arm64/boot/Image

